#!/bin/sh /etc/rc.common
USE_PROCD=1
START=96
STOP=10

PROG=/usr/sbin/test-service

start_service() {
    procd_open_instance test-service
    procd_set_param command "$PROG"
    procd_set_param respawn 3600 5 5
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

service_started() {
    ( ubus wait_for TestService 30 && /etc/init.d/tr181-device restart ) &
}

stop_service() {
    kill -TERM "$(pidof test-service)" 2>/dev/null
}
